/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package potatolcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ard_actuadores implements lcm.lcm.LCMEncodable
{
    public byte pulso_frecuencia;
    public byte cola_posicion;
    public byte cola_velocidad;
    public byte mejillas_rojo;
    public byte mejillas_verde;
    public byte mejillas_azul;
 
    public ard_actuadores()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9652a3614c98d075L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(potatolcm.ard_actuadores.class))
            return 0L;
 
        classes.add(potatolcm.ard_actuadores.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.pulso_frecuencia); 
 
        outs.writeByte(this.cola_posicion); 
 
        outs.writeByte(this.cola_velocidad); 
 
        outs.writeByte(this.mejillas_rojo); 
 
        outs.writeByte(this.mejillas_verde); 
 
        outs.writeByte(this.mejillas_azul); 
 
    }
 
    public ard_actuadores(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ard_actuadores(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static potatolcm.ard_actuadores _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        potatolcm.ard_actuadores o = new potatolcm.ard_actuadores();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.pulso_frecuencia = ins.readByte();
 
        this.cola_posicion = ins.readByte();
 
        this.cola_velocidad = ins.readByte();
 
        this.mejillas_rojo = ins.readByte();
 
        this.mejillas_verde = ins.readByte();
 
        this.mejillas_azul = ins.readByte();
 
    }
 
    public potatolcm.ard_actuadores copy()
    {
        potatolcm.ard_actuadores outobj = new potatolcm.ard_actuadores();
        outobj.pulso_frecuencia = this.pulso_frecuencia;
 
        outobj.cola_posicion = this.cola_posicion;
 
        outobj.cola_velocidad = this.cola_velocidad;
 
        outobj.mejillas_rojo = this.mejillas_rojo;
 
        outobj.mejillas_verde = this.mejillas_verde;
 
        outobj.mejillas_azul = this.mejillas_azul;
 
        return outobj;
    }
 
}

