/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package potatolcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ard_orden_pulso implements lcm.lcm.LCMEncodable
{
    public byte prioridad;
    public byte frecuencia;
 
    public ard_orden_pulso()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xdc8e79c937e6e959L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(potatolcm.ard_orden_pulso.class))
            return 0L;
 
        classes.add(potatolcm.ard_orden_pulso.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.prioridad); 
 
        outs.writeByte(this.frecuencia); 
 
    }
 
    public ard_orden_pulso(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ard_orden_pulso(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static potatolcm.ard_orden_pulso _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        potatolcm.ard_orden_pulso o = new potatolcm.ard_orden_pulso();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.prioridad = ins.readByte();
 
        this.frecuencia = ins.readByte();
 
    }
 
    public potatolcm.ard_orden_pulso copy()
    {
        potatolcm.ard_orden_pulso outobj = new potatolcm.ard_orden_pulso();
        outobj.prioridad = this.prioridad;
 
        outobj.frecuencia = this.frecuencia;
 
        return outobj;
    }
 
}

