/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package potatolcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ard_orden_mejillas implements lcm.lcm.LCMEncodable
{
    public byte prioridad;
    public byte rojo;
    public byte verde;
    public byte azul;
 
    public ard_orden_mejillas()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2faf71b94ce2692bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(potatolcm.ard_orden_mejillas.class))
            return 0L;
 
        classes.add(potatolcm.ard_orden_mejillas.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.prioridad); 
 
        outs.writeByte(this.rojo); 
 
        outs.writeByte(this.verde); 
 
        outs.writeByte(this.azul); 
 
    }
 
    public ard_orden_mejillas(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ard_orden_mejillas(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static potatolcm.ard_orden_mejillas _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        potatolcm.ard_orden_mejillas o = new potatolcm.ard_orden_mejillas();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.prioridad = ins.readByte();
 
        this.rojo = ins.readByte();
 
        this.verde = ins.readByte();
 
        this.azul = ins.readByte();
 
    }
 
    public potatolcm.ard_orden_mejillas copy()
    {
        potatolcm.ard_orden_mejillas outobj = new potatolcm.ard_orden_mejillas();
        outobj.prioridad = this.prioridad;
 
        outobj.rojo = this.rojo;
 
        outobj.verde = this.verde;
 
        outobj.azul = this.azul;
 
        return outobj;
    }
 
}

